if(EXISTS "/home/igellai/projects/bseal-cpp-skeleton/build-gui-test/tests/bseal_integration_gtests[1]_tests.cmake")
  include("/home/igellai/projects/bseal-cpp-skeleton/build-gui-test/tests/bseal_integration_gtests[1]_tests.cmake")
else()
  add_test(bseal_integration_gtests_NOT_BUILT bseal_integration_gtests_NOT_BUILT)
endif()
